[server]

db_root = "/data/chain_data"
api_http_addr = "0.0.0.0:13413"
chain_validation_mode = "Disabled"
archive_mode = true
run_tui = false
run_test_miner = false

[server.p2p_config]

host = "0.0.0.0"
port = 13414
seeding_type = "DNSSeed"


[server.p2p_config.capabilities]
bits = 15


[server.pool_config]
accept_fee_base = 1000000
max_pool_size = 50000
max_stempool_size = 50000
mineable_max_weight = 39976


[server.dandelion_config]
relay_secs = 600
embargo_secs = 180
patience_secs = 10
stem_probability = 90


[server.stratum_mining_config]

enable_stratum_server = false
stratum_server_addr = "127.0.0.1:13416"
attempt_time_per_block = 15
minimum_share_difficulty = 1
wallet_listener_url = "http://127.0.0.1:13415"
burn_reward = false


[logging]

log_to_stdout = true
stdout_log_level = "Warning"
log_to_file = false
file_log_level = "Debug"
log_file_path = "/data/grin-server.log"
log_file_append = true
log_max_size = 16777216
